# Generated by Django 4.0.3 on 2022-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age_person', models.CharField(max_length=50)),
                ('type_person', models.CharField(max_length=50)),
                ('create_person', models.CharField(max_length=50)),
                ('update_person', models.CharField(max_length=50)),
                ('status_person', models.CharField(max_length=50)),
            ],
        ),
    ]
