# Generated by Django 4.0.3 on 2022-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='create_person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='update_person',
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_ad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status_person',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
