# Generated by Django 4.0.3 on 2022-04-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_person_create_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_person',
            field=models.IntegerField(default='0'),
        ),
    ]
