# Generated by Django 4.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0009_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_url',
            field=models.URLField(default='Undefined', max_length=100),
        ),
    ]
