# Generated by Django 4.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0012_alter_student_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='social_url',
            field=models.URLField(default=0, max_length=100),
        ),
    ]
