# Generated by Django 4.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0015_alter_student_social_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
